[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = "{{ secrets['gh-access-token'] }}"

# A GitHub oauth application for this instance of homu:
app_client_id = "{{ secrets['app-client-id'] }}"
app_client_secret = "{{ secrets['app-client-secret'] }}"

[web]
port = 54856
secret = "{{ secrets['web-secret'] }}"

{% set ci_repos = {
    "angle": {},
    "app_units": {},
    "cgl-rs": {},
    "cocoa-rs": {},
    "core-foundation-rs": {},
    "core-graphics-rs": {},
    "core-text-rs": {},
    "devices": {},
    "download.servo.org": {},
    "dwrote-rs": {
        "travis": False,
        "appveyor": True,
    },
    "euclid": {},
    "fontsan": {},
    "futf": {},
    "gaol": {},
    "gleam": {},
    "glutin": {
        "master": "servo",
    },
    "heapsize": {},
    "highfive": {},
    "homu": {},
    "html5ever": {},
    "io-surface-rs": {},
    "ipc-channel": {
        "appveyor": True,
        "extra_reviewers": [ "antrik" ],
    },
    "libexpat": {},
    "libfontconfig": {},
    "libfreetype2": {},
    "mozjs": {
        "appveyor": True,
    },
    "osmesa-src": {},
    "rust-azure": {},
    "rust-bindgen": {
        "extra_reviewers": [ "fitzgen" ],
    },
    "rust-cssparser": {},
    "rust-fnv": {},
    "rust-fontconfig": {},
    "rust-freetype": {},
    "rust-glx": {},
    "rust-harfbuzz": {},
    "rust-layers": {},
    "rust-mozjs": {
        "appveyor": True,
    },
    "rust-png": {},
    "rust-quicksort": {},
    "rust-selectors": {},
    "rust-smallvec": {},
    "rust-stb-image": {},
    "rust-url": {},
    "rust-websocket": {
      "master": "servo",
    },
    "saltfs": {},
    "servo-starters": {},
    "skia": {},
    "string-cache": {},
    "tendril": {},
    "unicode-bidi": {},
    "unicode-script": {},
    "webrender": {},
    "webrender_traits": {},
} %}

{% set reviewers = [
    "aneeshusa",
    "asajeffrey",
    "bholley",
    "bzbarsky",
    "cbrewster",
    "edunham",
    "emilio",
    "frewsxcv",
    "glennw",
    "heycam",
    "jdm",
    "jgraham",
    "KiChjang",
    "kmcallister",
    "kvark",
    "larsbergstrom",
    "Manishearth",
    "mbrubeck",
    "metajack",
    "michaelwu",
    "mrobinson",
    "Ms2ger",
    "notriddle",
    "nox",
    "pcwalton",
    "saneyuki",
    "SimonSapin",
    "shinglyu",
    "upsuper",
    "Wafflespeanut",
    "zmike",
] %}

{% set operators = [
    "BorisChiou",
] %}

{% set try = [
    "askalski",
    "avadacatavra",
    "canaltinova",
    "chandler",
    "cynicaldevil",
    "danlrobertson",
    "dzbarsky",
    "jryans",
    "gsnedders",
    "GuillaumeGomez",
    "izgzhen",
    "magni-",
    "paulrouget",
    "stshine",
    "tschneidereit",
    "vvuk",
    "Yoric",
] %}

[repo.servo]
owner = "servo"
name = "servo"
reviewers = {{ reviewers + operators }}
try_users = {{ try }}

[repo.servo.github]
secret = "{{ secrets['gh-webhook-secret'] }}"

[repo.servo.buildbot]
url = "http://build.servo.org"
secret = "{{ secrets['buildbot-secret'] }}"
builders = [
    "linux-dev",
    "linux-rel-css",
    "linux-rel-wpt",
    "mac-dev-unit",
    "mac-rel-wpt1",
    "mac-rel-wpt2",
    "mac-rel-css",
    "android",
    "arm32",
    "arm64",
    "windows-gnu-dev",
    "windows-msvc-dev",
]
try_builders = [
    "linux-dev",
    "linux-rel-css",
    "linux-rel-wpt",
    "mac-dev-unit",
    "mac-rel-wpt1",
    "mac-rel-wpt2",
    "mac-rel-css",
    "android",
    "arm32",
    "arm64",
    "windows-gnu-dev",
    "windows-msvc-dev",
]
username = "{{ secrets['buildbot-http-user'] }}"
password = "{{ secrets['buildbot-http-pass'] }}"

# Disabled due to performance and instability
#[repo.servo.status.appveyor]
#context = 'continuous-integration/appveyor/branch'

# Standard per-repo configs (generated)

{% for name, repo in ci_repos.items() %}

[repo."{{ name }}"]
owner = "{{ repo.get("owner", "servo") }}"
name = "{{ name }}"
reviewers = {{ reviewers + operators + repo.get("extra_reviewers", []) }}
try_users = {{ try }}

[repo."{{ name }}".github]
secret = "{{ secrets['gh-webhook-secret'] }}"

{% if repo.get("travis", True) %}
[repo."{{ name }}".status.travis]
context = 'continuous-integration/travis-ci/push'
{% endif %}

{% if repo.get("appveyor", False) %}
[repo."{{ name }}".status.appveyor]
context = 'continuous-integration/appveyor/branch'
{% endif %}

{% if repo.get("master", False) %}
[repo."{{ name }}".branch]
master = "{{ repo.get("master") }}"
{% endif %}
{% endfor %}
